server {
    listen 9443;
    server_name _;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Esto sirve para que si recargan la página y no existe el archivo, no arroje error.
        try_files $uri $uri/ /index.html;
    }

    # Redirigir errores de servidor a la página estática /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
